#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

ROOT_DIR="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"

source $ROOT_DIR/vars

CLIENT_USER=pi
CLIENT_HOSTNAME=localhost
CLIENT_SSH_ORIGIN=${CLIENT_USER}@${CLIENT_HOSTNAME}
CLIENT_SSH_PORT=${Q_HOST_SSH_PORT}
CLIENT_RSYNC_SSH_ORIGIN=${CLIENT_SSH_ORIGIN}

function debug() {
    echo $@ 1>&2
}

function help() {
    debug "bake <command>"
    debug "  command"
    debug "    prerequisites  Install host system prerequisites to run QEMU."
    debug "    mount          Mount the image and store SSH installer into image."
    debug "    qemu           Run Raspberry Pi OS in QEMU."
    debug "    wait           Wait until SSH succeeds."
    debug "    ssh            SSH into the guest system."
    debug "    rsync"
    debug "      ssh          Invoke rsync over SSH."
    debug "    halt           SSH into the guest system and turn it off."
    debug "    get"
    debug "      user         Get the client user name."
    debug "      ssh"
    debug "        origin     Get the SSH destination user@hostname."
    debug "        port       Get the SSH port."
    exit -1
}

function pipe_ssh() {
    set +e
    trap "set -e" RETURN

    ssh \
        ${CLIENT_SSH_ORIGIN} \
        -p ${Q_HOST_SSH_PORT} \
        -i $Q_IDENTITY_SSH \
        -o StrictHostKeyChecking=no \
        -o 'ConnectionAttempts 1000' \
        $@ \
    ;
}

function pipe_ssh_exit() {
    pipe_ssh -T <<EOF
exit
EOF
}

function pipe_wait() {
    until pipe_ssh_exit
    do
        true
    done
}

function pipe_rsync_ssh() {
    set +e
    trap "set -e" RETURN

    rsync -e "ssh -p ${CLIENT_SSH_PORT} -i ${Q_IDENTITY_SSH}" $@
}

function stage_prerequisites() {
    sudo apt-get -y install \
        qemu-system-arm \
        qemu-user \
    ;
}

function stage_mount() {
    debug "Mount disk."
    LOOPBACK=$(sudo losetup -f)
    sudo losetup -P $LOOPBACK $Q_IMG
    PART_BOOT=$(mktemp -d)
    PART_USER=$(mktemp -d)
    sudo mount ${LOOPBACK}p1 $PART_BOOT
    sudo mount ${LOOPBACK}p2 $PART_USER

    function unmount_disks() {
        debug "Unmount disk."
        sudo umount $PART_BOOT
        sudo umount $PART_USER
        sudo losetup -d $LOOPBACK
    }
    trap unmount_disks EXIT

    debug "Generate custom SSH key."
    if [[ -f .user/id_rsa ]]
    then
        debug "Key exists, not regenerating."
    else
        mkdir -p .user/
        ssh-keygen -b 4096 -t rsa -f .user/id_rsa -q -N ""
    fi

    debug "Install SSH keys."
    sudo mkdir -p $PART_USER/home/pi/.ssh
    sudo cp .user/id_rsa.pub $PART_USER/home/pi/.ssh/authorized_keys

    debug "Install SSH server installer."
    sudo mv $PART_USER/etc/rc.local $PART_USER/etc/rc.local.original
    sudo cp $ROOT_DIR/mount/rc.local $PART_USER/etc/
}

function stage_qemu() {
    sudo qemu-system-arm \
        -M versatilepb \
        -cpu arm1176 \
        -m 256 \
        -append "root=/dev/sda2 rootfstype=ext4 rw" \
        -net nic \
        -net user,hostfwd=tcp::$Q_HOST_SSH_PORT-:22 \
        -net tap,ifname=vnet0,script=no,downscript=no \
        -drive file=$Q_IMG,format=raw \
        -dtb $Q_DTB \
        -kernel $Q_KERNEL \
        -no-reboot \
        $@ \
    ;
}

function stage_wait() {
    pipe_wait $@
}

function stage_ssh() {
    pipe_ssh $@
}

function stage_rsync() {
    if [ "$#" -lt 1 ]; then
        debug "Missing rsync argument."
        help
    fi
    COMMAND=$1
    shift
    case ${COMMAND} in
        ssh)
            stage_rsync_ssh $@
            ;;
        *)
            debug "Unknown rsync command \"${COMMAND}\"."
            help
            ;;
    esac
}

function stage_rsync_ssh() {
    pipe_rsync_ssh $@
}

function stage_halt() {
    stage_ssh $@ <<EOF
sudo reboot
EOF
}

function stage_get() {
    if [ "$#" -lt 1 ]; then
        debug "Missing get argument."
        help
    fi
    COMMAND=$1
    shift
    case ${COMMAND} in
        user)
            echo ${CLIENT_USER}
            ;;
        ssh)
            if [ "$#" -lt 1 ]; then
                debug "Missing get ssh argument."
                help
            fi
            COMMAND=$1
            shift
            case ${COMMAND} in
                origin)
                    echo ${CLIENT_SSH_ORIGIN}
                    ;;
                port)
                    echo ${CLIENT_SSH_PORT}
                    ;;
                *)
                    debug "Unknown get ssh origin command \"${COMMAND}\"."
                    help
                    ;;
            esac
            ;;
        *)
            debug "Unknown get subcommand \"${COMMAND}\"."
            help
            ;;
    esac
}


function stage_main() {
    if [ "$#" -lt 1 ]; then
        debug "Missing argument."
        help
    fi
    COMMAND=$1
    shift
    case ${COMMAND} in
        prerequisites)
            stage_prerequisites $@
            ;;
        mount)
            stage_mount $@
            ;;
        qemu)
            stage_qemu $@
            ;;
        wait)
            stage_wait $@
            ;;
        ssh)
            stage_ssh $@
            ;;
        rsync)
            stage_rsync $@
            ;;
        halt)
            stage_halt $@
            ;;
        get)
            stage_get $@
            ;;
        *)
            debug "Unknown command \"${COMMAND}\"."
            help
            ;;
    esac
}

stage_main $@